---
title: "20230218_luo_wu_proposal"
author:
date: "`r Sys.Date()`"
output: html_document
---

## Data preprocessing
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
## Load the necessary libraries
library(dplyr)
library(tidyr)
library(ggplot2)
library(psych) # Contains the winsor function and other helpful statistical tools
library(tidyverse) # Remember from last homework that dplyr is included in tidyverse
library(gridExtra)
library(corrplot)
library(patchwork)
library(stats)
library(caret)
```


```{r}
## Load the data
path_hrv <- "data/hrv_measurements.csv"
hrv_data <- read.csv(path_hrv)
head(hrv_data, 10)

path_subjects <- "data/participants.csv"
subjects_data <- read.csv(path_subjects)
head(subjects_data, 10)

dim(hrv_data)
dim(subjects_data)
```
```{r}
# unique(subjects_data$country)

## Merge the HRV data and age data using user_code as the common identifier
combined_hrv_data <- hrv_data %>%
  left_join(subjects_data, by = "user_code")

head(combined_hrv_data, 10)
dim(combined_hrv_data)
```
```{r}
## Drop unnecessary columns
combined_hrv_data <- combined_hrv_data %>%
  select(-c("rr_code", "how_sleep", "city", "rr_data", "tags")) #country
```

```{r}
head(combined_hrv_data, 10)
## Convert the age data from chr to factor
combined_hrv_data <- combined_hrv_data %>%
  mutate(age_range = factor(age_range))

## Print the levels of the age_range factor
levels(combined_hrv_data$age_range)

## Calculate BMI using height (cm) and weight (kg) information
combined_hrv_data <- combined_hrv_data %>%
  mutate(bmi = weight / ((height / 100) ^ 2))

head(combined_hrv_data$bmi, 20)
```


```{r}
## Check for missing values
sum(is.na(combined_hrv_data))
```
```{r}
## Impute missing values with mean
combined_hrv_data <- combined_hrv_data %>%
  mutate(across(c("rmssd", "sdnn", "pnn50", "bpm", "meanrr", "mxdmn", "mode", "amo", "lf", "hf", "vlf", "lfhf", "total_power", "how_feel", "how_mood", "bmi"), 
                ~ifelse(is.na(.), mean(., na.rm = TRUE), .)))
```

```{r}
## Normalize the data
combined_hrv_data_norm <- combined_hrv_data %>%
  mutate(across(c("rmssd", "sdnn", "pnn50", "bpm", "meanrr", "mxdmn", "mode", "amo", "lf", "hf", "vlf", "lfhf", "total_power", "how_feel", "how_mood", "bmi"), ~(. - mean(.)) / sd(.)))

head(combined_hrv_data_norm, 20)
```
```{r}
## 
ggplot(combined_hrv_data_norm, aes(x = meanrr)) +
  geom_histogram(bins=sqrt(nrow(combined_hrv_data_norm))) +
  theme_classic() +
  labs(title = "Histogram of Mean RR by Count", x = "Mean RR", y = "Count")

pairs.panels(combined_hrv_data_norm[4:8], pch=21, main="ppm, meanrr, mxdmn, sdnn, rmssd distribution")

all_rr_data <- as.numeric(unlist(strsplit(hrv_data$rr_data,",")))
boxplot(all_rr_data,ylab = "Heart beat invervals (ms)", main = "Box plot for Heart Beat Rate")
```


```{r}
set.seed(580)
train_id = sample(unique(combined_hrv_data_norm$user_code),0.8*length(unique(combined_hrv_data_norm$user_code)))
train_hrv <- combined_hrv_data_norm[combined_hrv_data_norm$user_code %in% train_id,]
test_hrv <- combined_hrv_data_norm[!combined_hrv_data_norm$user_code %in% train_id,]
```



## Data exploration and visualization
```{r}
## Descriptive statistics
summary(train_hrv)
```
```{r}
## Correlation matrix
corr_matrix <- cor(train_hrv[,c("rmssd", "sdnn", "pnn50", "bpm", "meanrr", "mxdmn", "mode", "amo", "lf", "hf", "vlf", "lfhf", "total_power", "how_feel", "how_mood", "bmi")])

# Order the correlation matrix using hierarchical clustering
corr_order <- stats::hclust(dist(corr_matrix))$order

# Create the correlation plot
corrplot(corr_matrix[corr_order, corr_order], method = "color", main="Correlation Matrix")
```

```{r}
## Histogram of RMSSD
# rMSSD — root mean square of successive differences for consecutive intervals.
hist(train_hrv$rmssd, breaks = 20, main = "Histogram of RMSSD", xlab = "RMSSD")
```
```{r}
## Boxplot of RMSSD and Age
plot(train_hrv$age_range, train_hrv$rmssd, xlab = "Age", ylab = "RMSSD", main = "Boxplot of RMSSD by Age")
```
```{r}
## Handle outliers
```

```{r}
## Boxplot of BMI by country
train_hrv %>%
  ggplot(aes(x = country, y = rmssd)) +
  geom_boxplot() +
  xlab("Country") +
  ylab("RMSSD") +
  ggtitle("Boxplot of RMSSD by Country") +
  theme_classic() +
  theme(axis.text.x = element_blank())
```


