---
title: "20230407_luo_wu_project"
author:
date: "`r Sys.Date()`"
output: pdf_document
---

## Data preprocessing
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
## Load the necessary libraries
library(dplyr)
library(tidyr)
library(ggplot2)
library(psych) # Contains the winsor function and other helpful statistical tools
library(tidyverse) # Remember from last homework that dplyr is included in tidyverse
library(gridExtra)
library(corrplot)
library(patchwork)
library(stats)
library(caret)
library(lubridate)
library(factoextra)
library(lme4)
library(ROCR)
library(class)
library(randomForest)
```


```{r}
## Load the data
path_hrv <- "data/hrv_measurements.csv"
hrv_data <- read.csv(path_hrv)
head(hrv_data, 10)

path_subjects <- "data/participants.csv"
subjects_data <- read.csv(path_subjects)
head(subjects_data, 10)

dim(hrv_data)
dim(subjects_data)
```
```{r}
# unique(subjects_data$country)

## Merge the HRV data and age data using user_code as the common identifier
combined_hrv_data <- hrv_data %>%
  left_join(subjects_data, by = "user_code")

head(combined_hrv_data, 10)
dim(combined_hrv_data)
```
```{r}
### have a look at rr_data
all_rr_data <- as.numeric(unlist(strsplit(hrv_data$rr_data,",")))
boxplot(all_rr_data,ylab = "Heart beat invervals (ms)", main = "Box plot for Heart Beat Rate")

## Drop unnecessary columns
combined_hrv_data <- combined_hrv_data %>%
  select(-c("user_code", "rr_code", "how_sleep", "city", "rr_data", "tags")) #country

# Convert columns to factors
combined_hrv_data$time_of_day = factor(combined_hrv_data$time_of_day)

## Convert the age data from chr to factor
combined_hrv_data <- combined_hrv_data %>%
  mutate(age_range = factor(age_range))

## Print the levels of the age_range factor
levels(combined_hrv_data$age_range)

# unique(combined_hrv_data$how_feel)
combined_hrv_data$how_feel <- factor(combined_hrv_data$how_feel, levels = c(-2, -1, 0, 1, 2))

# unique(combined_hrv_data$how_mood)
combined_hrv_data$how_mood <- factor(combined_hrv_data$how_mood, levels = c(-2, -1, 0, 1, 2))

combined_hrv_data$gender = factor(combined_hrv_data$gender)
combined_hrv_data$country = factor(combined_hrv_data$country)

#head(combined_hrv_data, 10)
#str(combined_hrv_data)
#summary(combined_hrv_data)

## Calculate a new column BMI using height (cm) and weight (kg) information
combined_hrv_data <- combined_hrv_data %>%
  mutate(bmi = weight / ((height / 100) ^ 2))

# unique(combined_hrv_data$symptoms_onset)
# create a new column with 2 categories
#combined_hrv_data$diagnosis <- ifelse(combined_hrv_data$symptoms_onset == "", "N", "Y")

# create 3 new columns, measurement_date, symptoms_date, covid_status
combined_hrv_data <- combined_hrv_data %>%
  mutate(
    measurement_date = as.Date(ymd_hms(measurement_datetime)),
    symptoms_date = as.Date(mdy(symptoms_onset), na.strings = ""),
    covid_status = ifelse(is.na(symptoms_date) | measurement_date < symptoms_date, 0, 1)
  )

combined_hrv_data$covid_status = factor(combined_hrv_data$covid_status)

head(combined_hrv_data)

# print the table of the new column
table(combined_hrv_data$covid_status)

## remove columns
hrv_df <- combined_hrv_data %>%
  select(-c("measurement_datetime", "symptoms_onset", "measurement_date", "symptoms_date"))

hrv_df
```

```{r}
## Check for missing values
sum(is.na(hrv_df))
colSums(is.na(hrv_df))

hrv_df
summary(hrv_df)
```
```{r}
# Calculate the mean height and mean BMI
mean_height <- mean(hrv_df$height, na.rm = TRUE)
mean_bmi <- mean(hrv_df$bmi, na.rm = TRUE)

# Impute the missing values with their respective means
hrv_df$height[is.na(hrv_df$height)] <- mean_height
hrv_df$bmi[is.na(hrv_df$bmi)] <- mean_bmi

# Check for missing values again to confirm the imputation
sum(is.na(hrv_df))
colSums(is.na(hrv_df))
```


```{r}
## Scale the data
hrv_df_scaled <- hrv_df %>%
  mutate(across(where(is.numeric) & -c(covid_status),  ~scale(.x)))

hrv_df_scaled
## Plot 
ggplot(hrv_df_scaled, aes(x = meanrr)) +
  geom_histogram(bins=sqrt(nrow(hrv_df_scaled))) +
  theme_classic() +
  labs(title = "Histogram of Mean RR by Count", x = "Mean RR", y = "Count")

pairs.panels(hrv_df_scaled[3:7], pch=21, main="bpm, meanrr, mxdmn, sdnn, rmssd distribution")
```

## Data exploration and visualization
```{r}
## Descriptive statistics
summary(hrv_df_scaled)

hrv_df_scaled

selected_columns <- c("rmssd", "sdnn", "pnn50", "bpm", "meanrr", "mxdmn", "mode", "amo", "lf", "hf", "vlf", "lfhf", "total_power", "bmi")
corr_matrix <- cor(hrv_df_scaled[, selected_columns])

# Calculate the distance matrix based on the correlation matrix
dist_matrix <- as.dist(1 - abs(corr_matrix))

# Order the correlation matrix using hierarchical clustering
corr_order <- stats::hclust(dist_matrix)$order

# Create the correlation plot
corrplot(corr_matrix[corr_order, corr_order], method = "color", main="Correlation Matrix")
```

```{r}
## Histogram of RMSSD
# rMSSD — root mean square of successive differences for consecutive intervals.
hist(hrv_df_scaled$rmssd, breaks = 20, main = "Histogram of RMSSD", xlab = "RMSSD")
```
```{r}
## Boxplot of RMSSD and Age
plot(hrv_df_scaled$age_range, hrv_df_scaled$rmssd, xlab = "Age", ylab = "RMSSD", main = "Boxplot of RMSSD by Age")
```


```{r}
## Boxplot of BMI by country
hrv_df_scaled %>%
  ggplot(aes(x = country, y = rmssd)) +
  geom_boxplot() +
  xlab("Country") +
  ylab("RMSSD") +
  ggtitle("Boxplot of RMSSD by Country") +
  theme_classic() +
  theme(axis.text.x = element_blank())
```

```{r}
summary(hrv_df_scaled)
```
  
```{r}
### remove rare countries, which is 0.0182 amount of observations
country_counts <- table(hrv_df_scaled$country)
low_count_countries <- names(country_counts)[country_counts <= 10]
hrv_df_scaled <- hrv_df_scaled %>% filter(!(country %in% low_count_countries))
```



```{r}
## Create a feature that measures the number of days since the onset of symptoms
# combined_hrv_data <- combined_hrv_data %>% mutate(days_since_symptoms = as.numeric(difftime(measurement_date, symptoms_date, units = "days")))

# head(combined_hrv_data)

set.seed(580)

# Split the scaled hrv data set using an 80:20 train/test split
hrv_data_split_idx <- createDataPartition(hrv_df_scaled$covid_status, p = 0.8, list = FALSE)

train_hrv_covid <- hrv_df_scaled[hrv_data_split_idx, ]
test_hrv_covid <- hrv_df_scaled[-hrv_data_split_idx, ]
```


```{r}
## Fit a logistic regression model
logit_model_1 <- glm(covid_status ~ ., data = train_hrv_covid, family = "binomial")

## Summary of the logistic regression model
summary(logit_model_1)
```

```{r}
hrv_df_numerics = train_hrv_covid %>% select_if(is.numeric)
hrv_pca <- prcomp(hrv_df_numerics, scale = TRUE)
fviz_eig(hrv_pca, addlabels = T, ncp = 16)
```
```{r}
### Base on the scree plot of PCA, we will choose the first 3 PCs
PCA_train = train_hrv_covid %>% select_if(is.factor)
PCA_train$PC1 = hrv_pca$x[,1]
PCA_train$PC2 = hrv_pca$x[,2]
PCA_train$PC3 = hrv_pca$x[,3]
logit_model_2 = glm(covid_status ~ ., data = PCA_train, family = "binomial")
summary(logit_model_2)
```

```{r}
logit_model_3 = glmer(covid_status ~ PC1 + PC2 + PC3 + time_of_day + how_feel + 
                        how_mood + gender + (1|age_range) + (1|country), 
                      data = PCA_train, family = "binomial")

summary(logit_model_3)
```

```{r}
test_hrv_numerics <- test_hrv_covid %>% select_if(is.numeric)
test_pca_transform <- predict(hrv_pca, newdata = test_hrv_numerics)
PCA_test = cbind(test_hrv_covid %>% select_if(is.factor), test_pca_transform[, 1:3])
```

```{r}
# logit_model_2
train_pred_prob <- predict(logit_model_2, PCA_train, type = "response")
train_roc_obj <- prediction(train_pred_prob, PCA_train$covid_status)
train_roc_perf <- performance(train_roc_obj, "sens", "spec")

# Find the best threshold
youdens_j <- train_roc_perf@y.values[[1]] + train_roc_perf@x.values[[1]] - 1
best_threshold <- train_roc_perf@alpha.values[[1]][which.max(youdens_j)]

# create confusion_matrix
predicted_class <- ifelse(predictions > best_threshold, 1, 0)
confusion_matrix <- table(Predicted = predicted_class, Actual = test_hrv_covid$covid_status)
print(confusion_matrix)

pred_prob <- predict(logit_model_2, PCA_test, type = "response")
roc_obj <- prediction(pred_prob, PCA_test$covid_status)
roc_perf <- performance(roc_obj, "tpr", "fpr")

# Plot the ROC curve
plot(roc_perf, col = "red", main = "ROC curve")
abline(0, 1, col = "gray", lty = 2)
text(x = 0.7, y = 0.3, labels = paste("AUC =", round(performance(roc_obj, "auc")@y.values[[1]], 4)), cex = 1)
```


```{r}
# logit_model_3
train_pred_prob <- predict(logit_model_3, PCA_train, type = "response")
train_roc_obj <- prediction(train_pred_prob, PCA_train$covid_status)
train_roc_perf <- performance(train_roc_obj, "sens", "spec")

# Find the best threshold
youdens_j <- train_roc_perf@y.values[[1]] + train_roc_perf@x.values[[1]] - 1
best_threshold <- train_roc_perf@alpha.values[[1]][which.max(youdens_j)]

# create confusion_matrix
predicted_class <- ifelse(predictions > best_threshold, 1, 0)
confusion_matrix <- table(Predicted = predicted_class, Actual = test_hrv_covid$covid_status)
print(confusion_matrix)

pred_prob <- predict(logit_model_3, PCA_test, type = "response")
roc_obj <- prediction(pred_prob, PCA_test$covid_status)
roc_perf <- performance(roc_obj, "tpr", "fpr")

# Plot the ROC curve
plot(roc_perf, col = "red", main = "ROC curve")
abline(0, 1, col = "gray", lty = 2)
text(x = 0.7, y = 0.3, labels = paste("AUC =", round(performance(roc_obj, "auc")@y.values[[1]], 4)), cex = 1)
```


```{r}
train_features <- PCA_train %>% select_if(is.numeric)
train_target <- PCA_train$covid_status
test_features <- PCA_test %>% select_if(is.numeric)
test_target <- PCA_test$covid_status

k_values <- 1:40
cv_errors <- sapply(k_values, function(k) {
  mean(knn.cv(train_features, train_target, k = k) != train_target)
})

best_k <- k_values[which.min(cv_errors)]

knn_model <- knn3(as.matrix(train_features), train_target, k = best_k)
```


```{r}
knn_pred_prob <- predict(knn_model, as.matrix(test_features), type = "prob")[, 2]

threshold <- 0.5
knn_pred_labels <- ifelse(knn_pred_prob > threshold, 1, 0)
confusion_matrix <- table(Predicted = knn_pred_labels, Actual = test_target)
print(confusion_matrix)

roc_obj <- prediction(knn_pred_prob, test_target)
roc_perf <- performance(roc_obj, "tpr", "fpr")

plot(roc_perf, col = "red", main = "ROC curve")
abline(0, 1, col = "gray", lty = 2)

auc_value <- performance(roc_obj, "auc")@y.values[[1]]
text(x = 0.7, y = 0.3, labels = paste("AUC =", round(auc_value, 4)), cex = 1)
```

```{r}
train_features <- PCA_train %>% select(-covid_status)
train_target <- PCA_train$covid_status
test_features <- PCA_test %>% select(-covid_status)
test_target <- PCA_test$covid_status

rf_model <- randomForest(x = train_features, y = train_target, importance = TRUE)
```

```{r}
rf_pred_prob <- predict(rf_model, test_features, type = "prob")[,2]
threshold <- 0.5
knn_pred_labels <- ifelse(rf_pred_prob > threshold, 1, 0)
confusion_matrix <- table(Predicted = knn_pred_labels, Actual = test_target)
print(confusion_matrix)

roc_obj <- prediction(rf_pred_prob, test_target)
roc_perf <- performance(roc_obj, "tpr", "fpr")

plot(roc_perf, col = "red", main = "ROC curve")
abline(0, 1, col = "gray", lty = 2)

auc_value <- performance(roc_obj, "auc")@y.values[[1]]
text(x = 0.7, y = 0.3, labels = paste("AUC =", round(auc_value, 4)), cex = 1)
```

